src/Internship.Web/Areas/Identity/Controllers/LoginController.cs
using DNTBreadCrumb.Core;
using DNTCaptcha.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System.Threading.Tasks;
using DNTCommon.Web.Core;
using Internship.Infrastructure.Services.Contracts.Identity;
using Internship.Core.DomainModels.ViewModel.Identity.Settings;
using Internship.Core.Common.GuardToolkit;
using Internship.Core.DomainModels.ViewModel.Identity;

namespace Internship.Web.Areas.Identity.Controllers
{
    [Area(AreaConstants.IdentityArea)]
    [AllowAnonymous]
    [BreadCrumb(Title = "ورود به سیستم", UseDefaultRouteUrl = true, Order = 0)]
    public class LoginController : Controller
    {
        private readonly ILogger<LoginController> _logger;
        private readonly IApplicationSignInManager _signInManager;
        private readonly IApplicationUserManager _userManager;
        private readonly IOptionsSnapshot<SiteSettings> _siteOptions;

        public LoginController(
            IApplicationSignInManager signInManager,
            IApplicationUserManager userManager,
            IOptionsSnapshot<SiteSettings> siteOptions,
            ILogger<LoginController> logger)
        {
            _signInManager = signInManager;
            _signInManager.CheckArgumentIsNull(nameof(_signInManager));

            _userManager = userManager;
            _userManager.CheckArgumentIsNull(nameof(_userManager));

            _siteOptions = siteOptions;
            _siteOptions.CheckArgumentIsNull(nameof(_siteOptions));

            _logger = logger;
            _logger.CheckArgumentIsNull(nameof(_logger));
        }

        //[BreadCrumb(Title = "ایندکس", Order = 1)]
        //[NoBrowserCache]
        //public IActionResult Index(string returnUrl = null)
        //{
        //    ViewData["ReturnUrl"] = returnUrl;
        //    return View();
        //}

        [BreadCrumb(Title = "ایندکس", Order = 1)]
        [NoBrowserCache]
        public IActionResult Index(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        //[ValidateDNTCaptcha(CaptchaGeneratorLanguage = DNTCaptcha.Core.Providers.Language.Persian)]
        public async Task<IActionResult> Index(LoginViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            //if (ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(model.Username);
                if (user == null)
                {
                    ModelState.AddModelError(string.Empty, "نام کاربری و یا کلمه‌ی عبور وارد شده معتبر نیستند.");
                    return View(model);
                }

                if (!user.IsActive)
                {
                    ModelState.AddModelError(string.Empty, "اکانت شما غیرفعال شده‌است.");
                    return View(model);
                }

                if (_siteOptions.Value.EnableEmailConfirmation &&
                    !await _userManager.IsEmailConfirmedAsync(user))
                {
                    ModelState.AddModelError("", "لطفا به پست الکترونیک خود مراجعه کرده و ایمیل خود را تائید کنید!");
                    return View(model);
                }

                var result = await _signInManager.PasswordSignInAsync(
                                        model.Username,
                                        model.Password,
                                        model.RememberMe,
                                        lockoutOnFailure: true);
                if (result.Succeeded)
                {
                    _logger.LogInformation(1, $"{model.Username} logged in.");
                    //if (Url.IsLocalUrl(returnUrl))
                    //{
                    //    return Redirect(returnUrl);
                    //}
                    if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1 && returnUrl.StartsWith("/")
                        && !returnUrl.StartsWith("//") && !returnUrl.StartsWith("/\\"))
                    {
                        return Redirect(returnUrl);
                    }
                    return RedirectToAction(nameof(HomeController.Index), "Home");
                }

                if (result.RequiresTwoFactor)
                {
                    return RedirectToAction(
                        nameof(TwoFactorController.SendCode),
                        "TwoFactor",
                        new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                }

                if (result.IsNotAllowed)
                {
                    ModelState.AddModelError(string.Empty, "عدم دسترسی ورود.");
                    return View(model);
                }

                ModelState.AddModelError(string.Empty, "نام کاربری و یا کلمه‌ی عبور وارد شده معتبر نیستند.");
                return View(model);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        public async Task<IActionResult> LogOff()
        {
            var user = User.Identity.IsAuthenticated ? await _userManager.FindByNameAsync(User.Identity.Name) : null;
            await _signInManager.SignOutAsync();
            if (user != null)
            {
                await _userManager.UpdateSecurityStampAsync(user);
                _logger.LogInformation(4, $"{user.UserName} logged out.");
            }

            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
    }
}

src/Internship.Web/Areas/Identity/Controllers/RolesManagerController.cs
using Internship.Core.Common.GuardToolkit;
using Internship.Core.Common.IdentityToolkit;



using Internship.Core.DomainModels.ViewModel.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Threading.Tasks;

using DNTBreadCrumb.Core;
using DNTCommon.Web.Core;
using Internship.Infrastructure.Services.Identity;
using Internship.Infrastructure.Services.Contracts.Identity;
using Internship.Core.DomainModels.Entity.Identity;

namespace Internship.Web.Areas.Identity.Controllers
{
    [Authorize(Roles = ConstantRoles.Admin)]
    [Area(AreaConstants.IdentityArea)]
    [BreadCrumb(Title = "مدیریت نقش‌ها", UseDefaultRouteUrl = true, Order = 0)]
    public class RolesManagerController : Controller
    {
        private const string RoleNotFound = "نقش درخواستی یافت نشد.";
        private const int DefaultPageSize = 7;

        private readonly IApplicationRoleManager _roleManager;

        public RolesManagerController(IApplicationRoleManager roleManager)
        {
            _roleManager = roleManager;
            _roleManager.CheckArgumentIsNull(nameof(_roleManager));
        }

        [BreadCrumb(Title = "ایندکس", Order = 1)]
        public IActionResult Index()
        {
            var roles = _roleManager.GetAllCustomRolesAndUsersCountList();
            return View(roles);
        }

        [AjaxOnly]
        public async Task<IActionResult> RenderRole([FromBody]ModelIdViewModel model)
        {
            if (string.IsNullOrWhiteSpace(model?.Id))
            {
                return PartialView("_Create");
            }

            var role = await _roleManager.FindByIdAsync(model.Id);
            if (role == null)
            {
                ModelState.AddModelError("", RoleNotFound);
                return PartialView("_Create");
            }
            return PartialView("_Create", model: new RoleViewModel { Id = role.Id.ToString(), Name = role.Name });
        }

        [AjaxOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditRole(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = await _roleManager.FindByIdAsync(model.Id);
                if (role == null)
                {
                    ModelState.AddModelError("", RoleNotFound);
                }
                else
                {
                    role.Name = model.Name;
                    var result = await _roleManager.UpdateAsync(role);
                    if (result.Succeeded)
                    {
                        return Json(new { success = true });
                    }
                    ModelState.AddErrorsFromResult(result);
                }
            }
            return PartialView("_Create", model: model);
        }

        [AjaxOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddRole(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _roleManager.CreateAsync(new Role(model.Name));
                if (result.Succeeded)
                {
                    return Json(new { success = true });
                }
                ModelState.AddErrorsFromResult(result);
            }
            return PartialView("_Create", model: model);
        }

        [AjaxOnly]
        public async Task<IActionResult> RenderDeleteRole([FromBody]ModelIdViewModel model)
        {
            if (string.IsNullOrWhiteSpace(model?.Id))
            {
                return PartialView("_Delete");
            }

            var role = await _roleManager.FindByIdAsync(model.Id);
            if (role == null)
            {
                ModelState.AddModelError("", RoleNotFound);
                return PartialView("_Delete");
            }
            return PartialView("_Delete", model: new RoleViewModel { Id = role.Id.ToString(), Name = role.Name });
        }

        [AjaxOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(RoleViewModel model)
        {
            var role = await _roleManager.FindByIdAsync(model.Id);
            if (role == null)
            {
                ModelState.AddModelError("", RoleNotFound);
            }
            else
            {
                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return Json(new { success = true });
                }
                ModelState.AddErrorsFromResult(result);
            }
            return PartialView("_Delete", model: model);
        }

        [BreadCrumb(Title = "لیست کاربران دارای نقش", Order = 1)]
        public async Task<IActionResult> UsersInRole(int? id, int? page = 1, string field = "Id", SortOrder order = SortOrder.Ascending)
        {
            if (id == null)
            {
                return View("Error");
            }

            var model = await _roleManager.GetPagedApplicationUsersInRoleListAsync(
                roleId: id.Value,
                pageNumber: page.Value - 1,
                recordsPerPage: DefaultPageSize,
                sortByField: field,
                sortOrder: order,
                showAllUsers: true);

            model.CurrentPage = page.Value;
            model.ItemsPerPage = DefaultPageSize;
            model.ShowFirstLast = true;

            if (HttpContext.Request.IsAjaxRequest())
            {
                return PartialView("~/Areas/Identity/Views/UsersManager/_UsersList.cshtml", model);
            }
            return View(model);
        }
    }
}

src/Internship.Web/Areas/Identity/Controllers/SystemLogController.cs
using Internship.Core.Common.GuardToolkit;

using DNTBreadCrumb.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Threading.Tasks;
using System;
using Internship.Infrastructure.Services.Identity;
using Internship.Infrastructure.Services.Contracts.Identity;

namespace Internship.Web.Areas.Identity.Controllers
{
    [Authorize(Roles = ConstantRoles.Admin)]
    [Area(AreaConstants.IdentityArea)]
    [BreadCrumb(Title = "لاگ سیستم", UseDefaultRouteUrl = true, Order = 0)]
    public class SystemLogController : Controller
    {
        private readonly IAppLogItemsService _appLogItemsService;

        public SystemLogController(
            IAppLogItemsService appLogItemsService)
        {
            _appLogItemsService = appLogItemsService;
            _appLogItemsService.CheckArgumentIsNull(nameof(_appLogItemsService));
        }

        [BreadCrumb(Title = "ایندکس", Order = 1)]
        public async Task<IActionResult> Index(
                        string logLevel = "",
                        int pageNumber = 1,
                        int pageSize = -1,
                        string sort = "desc")
        {
            var itemsPerPage = 10;
            if (pageSize > 0)
            {
                itemsPerPage = pageSize;
            }

            var model = await _appLogItemsService.GetPagedAppLogItemsAsync(
                pageNumber, itemsPerPage, sort == "desc" ? SortOrder.Descending : SortOrder.Ascending, logLevel);
            model.LogLevel = logLevel;
            model.Paging.CurrentPage = pageNumber;
            model.Paging.ItemsPerPage = itemsPerPage;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogItemDelete(int id)
        {
            await _appLogItemsService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogDeleteAll(string logLevel = "")
        {
            await _appLogItemsService.DeleteAllAsync(logLevel);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogDeleteOlderThan(string logLevel = "", int days = 5)
        {
            var cutoffUtc = DateTimeOffset.UtcNow.AddDays(-days);
            await _appLogItemsService.DeleteOlderThanAsync(cutoffUtc, logLevel);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/Internship.Web/Areas/Identity/Controllers/UserCardController.cs
using System.Threading.Tasks;
using Internship.Core.Common.GuardToolkit;
using Internship.Core.Common.IdentityToolkit;

using Internship.Core.DomainModels.ViewModel.Identity;
using DNTBreadCrumb.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Internship.Infrastructure.Services.Contracts.Identity;
using Internship.Infrastructure.Services.Identity;

namespace Internship.Web.Areas.Identity.Controllers
{
    [AllowAnonymous]
    [Area(AreaConstants.IdentityArea)]
    [BreadCrumb(Title = "برگه‌ی کاربری", UseDefaultRouteUrl = true, Order = 0)]
    public class UserCardController : Controller
    {
        private readonly IApplicationUserManager _userManager;
        private readonly IApplicationRoleManager _roleManager;

        public UserCardController(
            IApplicationUserManager userManager,
            IApplicationRoleManager roleManager)
        {
            _userManager = userManager;
            _userManager.CheckArgumentIsNull(nameof(_userManager));

            _roleManager = roleManager;
            _roleManager.CheckArgumentIsNull(nameof(_roleManager));
        }

        [BreadCrumb(Title = "ایندکس", Order = 1)]
        public async Task<IActionResult> Index(int? id)
        {
            if (!id.HasValue && User.Identity.IsAuthenticated)
            {
                id = User.Identity.GetUserId<int>();
            }

            if (!id.HasValue)
            {
                return View("Error");
            }

            var user = await _userManager.FindByIdIncludeUserRolesAsync(id.Value);
            if (user == null)
            {
                return View("NotFound");
            }

            var model= new UserCardItemViewModel
            {
                User = user,
                ShowAdminParts = User.IsInRole(ConstantRoles.Admin),
                Roles = await _roleManager.GetAllCustomRolesAsync(),
                ActiveTab = UserCardItemActiveTab.UserInfo
            };
            return View(model);
        }

        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> EmailToImage(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var fileContents = await _userManager.GetEmailImageAsync(id);
            return new FileContentResult(fileContents, "image/png");
        }

        [BreadCrumb(Title = "لیست کاربران آنلاین", Order = 1)]
        public IActionResult OnlineUsers()
        {
            return View();
        }
    }
}

src/Internship.Web/Views/Shared/AccessDenied.cshtml
@{
    ViewData["Title"] = "عدم دسترسی!";
    this.Context.Response.StatusCode = (int)HttpStatusCode.Unauthorized;
}

<div class="card panel-danger mt-5">
    <div class="card-header">
        <h5 class="card-title">@ViewData["Title"]</h5>
    </div>
    <div class="card-body">
        متاسفانه شما مجوز دسترسی به صفحه‌ی درخواستی را ندارید.
    </div>
</div>

src/Internship.Web/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "یافت نشد!";
    this.Context.Response.StatusCode = (int)HttpStatusCode.Gone;
}

<div class="mt-5">
    <div class="alert alert-warning">
        <h1><span aria-hidden="true" class="fas fa-warning"></span>خطا</h1>
        <h3>اطلاعات درخواستی یافت نشد.</h3>
    </div>
</div>

src/Internship.Web/Views/Shared/_AdminMenu.cshtml
<div class="navbar-nav">
    <div class="dropdown">
        <a class="nav-item nav-link dropdown-toggle" data-toggle="dropdown"
           id="adminDropdown" aria-haspopup="true"
           aria-expanded="false" href="#">
            منوی مدیریتی
        </a>
        <div class="dropdown-menu" aria-labelledby="adminDropdown">
                <a class="dropdown-item" asp-controller="UsersManager" asp-action="Index" asp-area="@AreaConstants.IdentityArea">
                    <i class="fas fa-user mr-1" aria-hidden="true"></i>
                    مدیریت کاربران
                </a>
                <a class="dropdown-item" asp-controller="RolesManager" asp-action="Index" asp-area="@AreaConstants.IdentityArea">
                    <i class="fas fa-object-group mr-1" aria-hidden="true"></i>
                    مدیریت نقش‌های سیستم
                </a>
                @*<a class="dropdown-item" asp-controller="SystemLog" asp-action="Index" asp-area="@AreaConstants.IdentityArea">
                    <i class="fas fa-bell mr-1" aria-hidden="true"></i>
                    گزارش رخ‌دادهای سیستم
                </a>*@
        </div>
    </div>
</div>

src/Internship.Web/Views/Shared/_Breadcrumb.cshtml
@*@using Research.City.Admin.Toolkit

@{ BreadCrumb breadCrumb = ViewBag.BreadCrumb; }*@


@*@if (breadCrumb != null)
{
    <div class="normalheader small-header">
        <div class="hpanel">
            <div class="panel-body">
                @if (breadCrumb.Links != null)
                {
                    <div id="hbreadcrumb" class="pull-right">
                        <ol class="hbreadcrumb breadcrumb">
                            <li><a asp-controller="Home" asp-action="Index">داشبورد</a></li>

                            @foreach (var item in breadCrumb.Links)
                            {
                                <li class="@(string.IsNullOrWhiteSpace(item.Link) ? "active" : "")">
                                    @if (string.IsNullOrWhiteSpace(item.Link))
                                    {
                                        <span>@item.Title</span>
                                    }
                                    else
                                    {
                                        <a href="@item.Link">@item.Title</a>
                                    }
                                </li>
                            }
                        </ol>
                    </div>
                }

            
                <h2 class="font-light m-b-xs">
                    @ViewBag.Title
                </h2>
                <small>
                    @(ViewBag.Description ?? ViewBag.Title)
                </small>
            </div>
        </div>
    </div>
}*@

src/Internship.Web/Views/Shared/_Clock.cshtml
@using Alamut.Helpers.DateTime
@using DNTPersianUtils.Core

<div style="text-align: center; margin-top: 25px;">
    <div>امروز</div>
    <div>@DateTime.Now.GetPersianDateString().ToPersianNumbers()</div>
</div>

<div id="canvasClock" style="visibility: hidden;">
    <canvas class="canvas center-block" id="analogClock" width="240" height="240" style="max-width: 100%;"></canvas>

    <div class="text-center" dir="ltr" style="direction: ltr;">
        <div id="digitalClock">00:00:00 AM</div>
    </div>
</div>

<script>
    function drawClock(drawPlace, timestamp) {
        var canvas = document.getElementById(drawPlace),
            context = canvas.getContext("2d"),
            centerX = canvas.width / 2,
            centerY = canvas.height / 2,
            radius = canvas.width / 2 - 20;

        context.clearRect(0, 0, canvas.width, canvas.height);
        context.lineCap = "round";
        context.beginPath();
        context.arc(centerX, centerY, radius - 10, 0, 2 * Math.PI, false);
        context.fillStyle = '#ccc';
        context.fill();
        context.closePath();
        context.restore();

        context.beginPath();
        context.arc(centerX, centerY, radius - 14, 0, 2 * Math.PI, false);
        context.fillStyle = '#fff';
        context.fill();
        context.closePath();
        context.restore();

        // Center Circle
        context.beginPath();
        context.arc(centerX, centerY, 4, 0, 2 * Math.PI, false);
        context.lineWidth = 3;
        context.strokeStyle = '#555';
        context.stroke();
        context.closePath();
        context.restore();

        context.translate(centerX, centerY);

        context.fillStyle = '#555';
        context.font = radius * 0.18 + "px Arial";
        context.textBaseline = "middle";
        context.textAlign = "center";
        for (num = 0; num < 12; num++) {
            ang = (num + 1) * Math.PI / 6;
            context.rotate(ang);
            context.translate(0, -radius * 0.60);
            context.rotate(-ang);
            context.fillText((num + 1).toString(), 0, 0);
            context.rotate(ang);
            context.translate(0, radius * 0.60);
            context.rotate(-ang);
        }

        for (var i = 1; i <= 60; i++) {
            angle = Math.PI / 30 * i;
            sineAngle = Math.sin(angle);
            cosAngle = -Math.cos(angle);

            if (i % 5 == 0) {
                context.lineWidth = 2;
                iPointX = sineAngle * (radius - 25);
                iPointY = cosAngle * (radius - 25);
                oPointX = sineAngle * (radius - 20);
                oPointY = cosAngle * (radius - 20);
            } else {
                context.lineWidth = 0.8;
                iPointX = sineAngle * (radius - 22);
                iPointY = cosAngle * (radius - 22);
                oPointX = sineAngle * (radius - 20);
                oPointY = cosAngle * (radius - 20);
            }

            context.beginPath();
            context.moveTo(iPointX, iPointY);
            context.lineTo(oPointX, oPointY);
            context.stroke();
        }

        var now = timestamp,

            hrs = now.getHours(),
            min = now.getMinutes(),
            sec = now.getSeconds();

        // Set Hands Variables
        var sangle = (Math.PI / 30 * sec),
            sPointX = Math.sin(sangle) * (radius - 50),
            sPointY = -Math.cos(sangle) * (radius - 50);

        // Draw seconds hand
        context.beginPath();
        context.lineWidth = 2;
        context.moveTo(0, 0);
        context.strokeStyle = "#888";
        context.lineTo(sPointX, sPointY);
        context.stroke();
        context.closePath();

        // Draw minutes hand
        context.beginPath();
        context.lineWidth = 4;
        context.strokeStyle = "#555555";
        sangle = (Math.PI / 30 * (min + (sec / 60)));
        sPointX = Math.sin(sangle) * (radius - 48);
        sPointY = -Math.cos(sangle) * (radius - 48);
        context.moveTo(0, 0);
        context.lineTo(sPointX, sPointY);
        context.stroke();
        context.closePath();

        // Draw hours hand
        context.beginPath();
        context.lineWidth = 6;
        context.strokeStyle = "#555555";
        sangle = (Math.PI / 6 * (hrs + (min / 65) + (sec / 3600)));
        sPointX = Math.sin(sangle) * (radius - 65);
        sPointY = -Math.cos(sangle) * (radius - 65);
        context.moveTo(0, 0);
        context.lineTo(sPointX, sPointY);
        context.stroke();
        context.closePath();

        context.restore();
        context.translate(-centerX, -centerY);
    }

    var duration = 0;
    var delay = 0;
    var year = 0;
    var month = 0;
    var day = 0;
    var hour = 0;
    var minute = 0;
    var second = 0;
    var millisecond = 0;


    function initTime() {
        var result = '@DateTime.Now.ToString("yyyy MM dd HH mm ss ff")';
        // var result = "2016 05 15 11 53 44 68";
        var items = result.toString().split(' ');
        year = Number(items[0]);
        month = Number(items[1]);
        day = Number(items[2]);
        hour = Number(items[3]);
        minute = Number(items[4]);
        second = Number(items[5]) + 1;
        millisecond = Number(items[6]);
    }

    initTime();

    setInterval(function () {
        $("#canvasClock").css("visibility", 'visible');
        var d = new Date(year, month, day, hour, minute, second, millisecond);
        d.setSeconds(d.getSeconds() + duration + delay);

        drawClock('analogClock', d);

        duration = duration + 1;

        var hh = d.getHours();
        var m = d.getMinutes();
        var s = d.getSeconds();

        var dd = "AM";
        var h = hh;

        if (h >= 12) {
            h = hh - 12;
            dd = "PM";
        }

        if (h == 0) {
            h = 12;
        }

        m = m < 10 ? "0" + m : m;
        s = s < 10 ? "0" + s : s;
        h = h < 10 ? "0" + h : h;

        document.getElementById('digitalClock').innerHTML = ('<div style="font-family: monospace;">' + h + ':' + m + ':' + s + ' ' + '<span>' + dd + '</span></div>');
    }, 1000);
</script>

src/Internship.Web/Views/Shared/_CustomValidationSummary.cshtml
@if (ViewData.ModelState.Any(keyValuePair => keyValuePair.Value.Errors.Any()))
{
    <div class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert">×</a>
        <h4>خطاهای اعتبارسنجی</h4>
        <div asp-validation-summary="ModelOnly"></div>
    </div>
}

src/Internship.Web/Views/Shared/_Message.cshtml
@using Microsoft.AspNetCore.Html
@using Newtonsoft.Json
@{
    var result = TempData["ServiceResult.Message"] as string;
    if (result != null)
    {

        @*<div class="alert alert-@((bool) TempData["ServiceResult.Succeed"] ? "success" : "danger") alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                <div>
                    @if (string.IsNullOrEmpty(result))
                    {
                        <span>
                            @((bool) TempData["ServiceResult.Succeed"] ? "عملیات با موفقیت انجام شد." : "خطا!")
                        </span>
                    }
                    else
                    {
                        <span>@result</span>
                    }
                </div>

            </div>*@

        <script>
            (function () {
                var result = {
                    Message: @(new HtmlString(JsonConvert.SerializeObject(result))),
                    Succeed: @(JsonConvert.SerializeObject(TempData["ServiceResult.Succeed"]))
                };

                showBeautyMessage(result);
            }());
        </script>
    }
}

src/Internship.Web/Views/Shared/_SidebarMenu.cshtml
@*<div id="OnlineUsers" dir="rtl">
    <cache expires-after="@TimeSpan.FromMinutes(1)">
        <vc:online-users numbers-to-take="5" minutes-to-take="5" show-more-items-link="true"></vc:online-users>
    </cache>
</div>

<div id="TodayBirthDays" dir="rtl">
    <cache expires-after="@TimeSpan.FromMinutes(5)">
        <vc:today-birth-days></vc:today-birth-days>
    </cache>
</div>*@

src/Internship.Web/Views/Shared/_UserMenu.cshtml
@using  Internship.Infrastructure.Services.Contracts.Identity
@inject IUsersPhotoService PhotoService
@{
    var displayName = User.Identity.GetUserDisplayName();
    var photoUrl = PhotoService.GetCurrentUserPhotoUrl();
}

<div class="navbar-nav">
    <div class="dropdown">
        <a class="nav-item nav-link dropdown-toggle" data-toggle="dropdown"
           id="userDropdown" aria-haspopup="true"
           aria-expanded="false" href="#">
            <img class="img-thumbnail userImage" src="@photoUrl" alt="@displayName" asp-append-version="true"
                 onerror="this.style.visibility = 'hidden';this.width=0; this.height=0;" />
            <span class="author">@displayName</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="userDropdown">
            <a class="dropdown-item" asp-controller="UserCard" asp-action="Index" asp-area="@AreaConstants.IdentityArea">
                <span class="mr-1 fas fa-user" aria-hidden="true"></span>
                برگه‌ی کاربری من
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" asp-controller="UserProfile" asp-action="Index" asp-area="@AreaConstants.IdentityArea">
                <span class="mr-1 fas fa-cog" aria-hidden="true"></span>
                تنظیمات کاربری من
            </a>
            @*<a class="dropdown-item" asp-controller="ChangePassword" asp-action="Index" asp-area="@AreaConstants.IdentityArea">
                    <span class="mr-1 fas fa-asterisk" aria-hidden="true"></span>
                    تغییر کلمه‌ی عبور
                </a>*@
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" asp-controller="Login" asp-action="LogOff" asp-area="@AreaConstants.IdentityArea">
                <span class="mr-1 fas fa-sign-out-alt" aria-hidden="true"></span>
                خروج
            </a>
        </div>
    </div>
</div>