src/Internship.Web/Controllers/Routine2/Routine2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Alamut.Utilities.Http;
using Internship.AppService.Helpers;
using Internship.Core.Common.IdentityToolkit;
using Internship.Core.DomainModels.DTO.Routine2;
using Internship.Core.DomainModels.SSOT;
using Internship.Infrastructure.Services.Routine2;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc; 
using Newtonsoft.Json; 

namespace Nahad.Admin.Controllers
{
    public class Routine2Controller : Controller
    {
        private readonly Routine2Repository _routine2Repository;  
        private readonly IUserResolverService _userResolverService;
        private readonly IHttpContextAccessor _contextAccessor;

        public Routine2Controller(Routine2Repository routinRepository
            , IUserResolverService userResolverService, IHttpContextAccessor contextAccessor)
        {
            _contextAccessor = contextAccessor;
            _routine2Repository = routinRepository;
            _userResolverService = userResolverService;
        }

        public IActionResult GetLogs(string routineIdE, string entityIdE)
        {
            var entityId = Convert.ToInt32(AESGCM.SimpleDecryptWithPassword(entityIdE, AppConfiguration.EncryptionSalt));
            var routineId = Convert.ToInt32(AESGCM.SimpleDecryptWithPassword(routineIdE, AppConfiguration.EncryptionSalt));

            var model = _routine2Repository.GetLogs(routineId, entityId);
            ViewBag.RoutineId = routineId;
            return View(model);
        }

        public IActionResult GetRoutineStepsByRoutineId(int routineId)
        {
            var model = _routine2Repository.GetRoutineStepsByRoutineId(routineId);
            return Json(model);
        }

        public IActionResult GetRoutine(int routineId)
        {
            var model = _routine2Repository.GetRoutineFull(routineId);
            return Json(model);
        }


        /// <summary>
        /// ارسال
        /// Notice, SMS, Email
        /// برای تست در همه روال‌ها
        /// </summary>
        //public async Task<IActionResult> SendNotice(int RoutineId, int EntityId, int FromStep, int ToStep, bool realSend = false)
        //{
        //    var Params = new
        //    {
        //        RoutineId,
        //        EntityId,
        //        FromStep,
        //        ToStep,
        //    };

        //    var userId = _contextAccessor.HttpContext.User.Identity.GetUserId();

        //    try
        //    {
        //        var Result = await _routine2Repository.SendNoticeAsync(new Routine2ChangeStepResult
        //        {
        //            RoutineId = RoutineId,
        //            EntityId = EntityId,
        //            FromStep = FromStep,
        //            ToStep = ToStep,
        //            UserId = userId,
        //        }, realSend);

        //        return Json(new { Params, Result });
        //    }
        //    catch (Exception ex)
        //    {
        //        return Json(new { Params, ex.Message });
        //    }
        //}


        //public IActionResult Autodash()
        //{
        //    _routine2Repository.Authodash();
        //    return Content("DONE Authodash");
        //}

        //public IActionResult Reminder()
        //{
        //    _routine2Repository.Reminder();
        //    return Content("DONE Reminder");
        //}
    }
}

src/Internship.Web/Views/Shared/_Routine2/_ChangeStep.cshtml
@using Internship.Core.DomainModels.Entity.Routine2
@model Internship.Core.DomainModels.ViewModel.Routine2.Routine2ChangeStep


<span title="@Model.Action"
      style="display: none;"
      id="routine_record_action_tooltip_@(Model.Action)_@Model.EntityId">
    <button type="button"
            id="routine_record_action_@(Model.Action)_@Model.EntityId"
            data-popover="Routine_Action_@(Model.Action)_@Model.EntityId"
            class="exir--transparent-btn">
        <i data-role="icon" class="pe-7s-play largeicon"></i>
    </button>
</span>

<div data-role="popover-content" id="Routine_Action_@(Model.Action)_@Model.EntityId">
    <form data-role="routine-ajax-form">
        <input type="hidden" name="Id" value="@Model.EntityId" />
        <input type="hidden" name="Action" value="@Model.Action" />

        <textarea class="form-control" name="Description"
                  oninvalid="this.setCustomValidity('لطفا پیش از ارسال، توضیحات را کامل نمایید')"
                  oninput="this.setCustomValidity('')"
                  style="resize: none; height: 180px; overflow: hidden;"></textarea>

        <input type="text" class="form-control" name="Description"
               oninvalid="this.setCustomValidity('لطفا پیش از ارسال، توضیحات را کامل نمایید')"
               oninput="this.setCustomValidity('')" />

        <button data-role="button" type="submit" class="btn btn-block m-t-xs">@Model.Action</button>
    </form>
</div>

src/Internship.Web/Views/Shared/_Routine2/_CustomAction.cshtml
@using Exir.Regate 



@try
{
    if (Model.Entity.RoutineStep == Model.Step)
    {
        @Html.Partial($"_CustomActions/_Step{Model.Step}")
    }
}
catch (Exception ex)
{
    <p>@ex.Message</p>
}

src/Internship.Web/Views/Shared/_Routine2/_DefaultActions.cshtml
@using Internship.Core.DomainModels.ViewModel.Routine2 
@using Internship.Core.DomainModels.SSOT
@model int


@Html.Partial("_Routine2/_ChangeStep", new Routine2ChangeStep(Model, Routine2Actions.F1))
@Html.Partial("_Routine2/_ChangeStep", new Routine2ChangeStep(Model, Routine2Actions.F2))
@Html.Partial("_Routine2/_ChangeStep", new Routine2ChangeStep(Model, Routine2Actions.F3))
@Html.Partial("_Routine2/_ChangeStep", new Routine2ChangeStep(Model, Routine2Actions.F4))
@Html.Partial("_Routine2/_ChangeStep", new Routine2ChangeStep(Model, Routine2Actions.F5))
@Html.Partial("_Routine2/_ChangeStep", new Routine2ChangeStep(Model, Routine2Actions.F6))
@Html.Partial("_Routine2/_ChangeStep", new Routine2ChangeStep(Model, Routine2Actions.F7))

src/Internship.Web/Views/Shared/_Routine2/_LogButton.cshtml
  

@*@{
    var entityIdE = AESGCM.SimpleEncryptWithPassword(Model.EntityId.ToString(), AppConfiguration.EncryptionSalt);
    var routineIdE = AESGCM.SimpleEncryptWithPassword(Model.RoutineId.ToString(), AppConfiguration.EncryptionSalt);
}


<a data-fancybox data-type="iframe" asp-controller="Routine2" asp-action="GetLogs" asp-route-routineIdE="@routineIdE" asp-route-entityIdE="@entityIdE">
    <i class="pe-7s-timer largeicon" title="تاریخچه" data-toggle="tooltip"></i>
</a>*@